import { CompanyData } from '@/types/company';

export const companyData: CompanyData = {
  name: 'TIM STROY',
  legalForm: 'ТОО',
  city: 'Алматы',
  description: 'Инженерно-строительная компания с международным опытом. Проектирование и монтаж инженерных систем для промышленных объектов, аэропортов и жилых комплексов.',
  tagline: 'Инженерные решения мирового уровня',

  stats: {
    currentProjects: 7,
    projectsCompleted: 80,
    trustedCompanies: 25,
  },

  services: [
    {
      id: 'water-supply',
      title: 'Водоснабжение',
      description: 'Комплексные системы водоснабжения для объектов любого масштаба',
      icon: 'Droplets',
      features: ['Холодное водоснабжение', 'Горячее водоснабжение', 'Насосные станции', 'Водоподготовка'],
    },
    {
      id: 'sewage',
      title: 'Канализация',
      description: 'Проектирование и монтаж канализационных систем',
      icon: 'Pipette',
      features: ['Внутренняя канализация', 'Наружная канализация', 'Ливневая канализация', 'Очистные сооружения'],
    },
    {
      id: 'hvac',
      title: 'Вентиляция и кондиционирование',
      description: 'Климатические системы для комфорта и производства',
      icon: 'Wind',
      features: ['Приточная вентиляция', 'Вытяжная вентиляция', 'Кондиционирование', 'Климат-контроль'],
    },
    {
      id: 'fire-protection',
      title: 'Пожаротушение',
      description: 'Автоматические системы пожарной безопасности',
      icon: 'Flame',
      features: ['Спринклерные системы', 'Дренчерные системы', 'Газовое пожаротушение', 'Пожарная сигнализация'],
    },
    {
      id: 'heating',
      title: 'Отопление',
      description: 'Эффективные системы отопления под ключ',
      icon: 'Thermometer',
      features: ['Радиаторное отопление', 'Тёплые полы', 'Тепловые пункты', 'Котельные'],
    },
    {
      id: 'electrical',
      title: 'Электроснабжение',
      description: 'Силовые и слаботочные электрические системы',
      icon: 'Zap',
      features: ['Силовые сети', 'Освещение', 'Слаботочные системы', 'Заземление'],
    },
    {
      id: 'boiler',
      title: 'Котельные',
      description: 'Строительство и модернизация котельных',
      icon: 'Factory',
      features: ['Газовые котельные', 'Электрические котельные', 'Модульные котельные', 'Реконструкция'],
    },
  ],

  projects: [
    {
      id: 'almaty-airport',
      title: 'Международный аэропорт Алматы',
      category: 'Инфраструктура',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2024,
      description: 'Крупнейший аэропорт Казахстана с пассажиропотоком более 7 млн человек в год. Выполнен полный комплекс инженерных работ для нового терминала площадью 50 000 м²: системы приточно-вытяжной вентиляции, центральное кондиционирование, автоматическое пожаротушение, холодное и горячее водоснабжение.',
      image: '/projects/airport-almaty.jpg',
      mapsUrl: 'https://maps.google.com/?q=Almaty+International+Airport',
      status: 'completed',
    },
    {
      id: 'astana-airport',
      title: 'Международный аэропорт Астана',
      category: 'Инфраструктура',
      location: 'Астана, Казахстан',
      country: 'Казахстан',
      year: 2017,
      description: 'Аэропорт столицы Казахстана, принимающий более 5 млн пассажиров ежегодно. Реализованы инженерные системы для расширения терминала: климатические установки с рекуперацией тепла, система автоматического пожаротушения, внутренние сети водоснабжения и водоотведения.',
      image: '/projects/airport-astana.jpg',
      mapsUrl: 'https://maps.google.com/?q=Astana+International+Airport',
      status: 'completed',
    },
    {
      id: 'turkestan-airport',
      title: 'Международный аэропорт Туркестан',
      category: 'Инфраструктура',
      location: 'Туркестан, Казахстан',
      country: 'Казахстан',
      year: 2020,
      description: 'Новый международный аэропорт, построенный в рамках программы развития туризма региона. Смонтированы системы центрального кондиционирования для зон ожидания, приточно-вытяжная вентиляция с фильтрацией, сети холодного и горячего водоснабжения.',
      image: '/projects/airport-turkestan.jpg',
      mapsUrl: 'https://maps.google.com/?q=Turkestan+Airport',
      status: 'completed',
    },
    {
      id: 'coca-cola-namangan',
      title: 'Coca-Cola Наманган',
      category: 'Промышленность',
      location: 'Наманган, Узбекистан',
      country: 'Узбекистан',
      year: 2022,
      description: 'Завод по производству безалкогольных напитков Coca-Cola Ichimligi в Наманганской области. Выполнен монтаж систем охлаждения технологического оборудования, промышленной вентиляции производственных цехов, трубопроводов для подачи сырья на линии розлива.',
      image: '/projects/coca-cola-namangan.jpg',
      mapsUrl: 'https://maps.google.com/?q=Namangan,+Uzbekistan',
      status: 'completed',
    },
    {
      id: 'coca-cola-shymkent',
      title: 'Coca-Cola Шымкент',
      category: 'Промышленность',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2024,
      description: 'Производственный комплекс Coca-Cola в южном регионе Казахстана. Смонтированы технологические трубопроводы из нержавеющей стали, системы промышленной вентиляции с очисткой воздуха, сети электроснабжения производственного оборудования.',
      image: '/projects/coca-cola-shymkent.jpg',
      mapsUrl: 'https://maps.google.com/?q=Shymkent,+Kazakhstan',
      status: 'completed',
    },
    {
      id: 'coca-cola-tajikistan',
      title: 'Coca-Cola Таджикистан',
      category: 'Промышленность',
      location: 'Душанбе, Таджикистан',
      country: 'Таджикистан',
      year: 2023,
      description: 'Расширение производственных мощностей завода в Душанбе. Выполнен монтаж инженерных систем для новой линии розлива ПЭТ-бутылок: охлаждение оборудования, промышленная вентиляция, внутренние сети водоснабжения.',
      image: '/projects/coca-cola-tajikistan.jpg',
      mapsUrl: 'https://maps.google.com/?q=Dushanbe,+Tajikistan',
      status: 'completed',
    },
    {
      id: 'coca-cola-tashkent',
      title: 'Coca-Cola Ташкент',
      category: 'Промышленность',
      location: 'Ташкент, Узбекистан',
      country: 'Узбекистан',
      year: 2023,
      description: 'Головной завод Coca-Cola в Узбекистане. Реализован проект расширения: смонтированы инженерные системы для новой производственной линии, включая охлаждение, вентиляцию, водоподготовку и электроснабжение.',
      image: '/projects/coca-cola-tashkent.jpg',
      mapsUrl: 'https://maps.google.com/?q=Tashkent,+Uzbekistan',
      status: 'completed',
    },
    {
      id: 'coca-cola-astana',
      title: 'Coca-Cola Астана',
      category: 'Промышленность',
      location: 'Астана, Казахстан',
      country: 'Казахстан',
      year: 2023,
      description: 'Производственный комплекс Coca-Cola в столице Казахстана. Выполнена модернизация инженерной инфраструктуры: замена систем охлаждения, обновление вентиляционного оборудования, монтаж автоматизированных систем управления.',
      image: '/projects/coca-cola-astana.jpg',
      mapsUrl: 'https://maps.google.com/?q=Astana,+Kazakhstan',
      status: 'completed',
    },
    {
      id: 'mcdonalds-almaty-dostyk',
      title: "McDonald's Достык Плаза",
      category: 'Ресторан',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2017,
      description: 'Ресторан быстрого питания в премиальном торговом центре Достык Плаза. Смонтированы мощные вытяжные системы для кухонной зоны, приточная вентиляция с подогревом воздуха, сплит-системы для зоны обслуживания, сети холодного и горячего водоснабжения.',
      image: '/projects/mcdonalds-dostyk.jpg',
      mapsUrl: 'https://maps.google.com/?q=Dostyk+Plaza+Almaty',
      status: 'completed',
    },
    {
      id: 'mcdonalds-astana',
      title: "Общепит быстрого питания «McDonald's»",
      category: 'Ресторан',
      location: 'Астана, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Сеть ресторанов McDonald\'s в столице Казахстана. Выполнен монтаж инженерных систем согласно международным стандартам бренда: системы вентиляции с очисткой воздуха, водоснабжение с системой фильтрации, электроснабжение кухонного оборудования.',
      image: '/projects/mcdonalds-astana.jpg',
      mapsUrl: 'https://maps.google.com/?q=McDonalds+Astana',
      status: 'completed',
    },
    {
      id: 'mega-center-plus',
      title: '«MEGA Center Plus» Расширение торгового центра',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2013,
      description: 'Расширение одного из крупнейших торговых центров Алматы на 25 000 м². Смонтированы системы центрального кондиционирования, приточно-вытяжная вентиляция с рекуперацией, автоматическое пожаротушение, внутренние сети водоснабжения и канализации.',
      image: '/projects/mega-center-plus.jpg',
      mapsUrl: 'https://maps.google.com/?q=Mega+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'ramstore-mega-center-plus',
      title: 'ТЦ «Ramstore Mega Center Plus»',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2013,
      description: 'Гипермаркет Ramstore в составе торгового комплекса MEGA. Выполнен монтаж систем холодоснабжения для продуктового отдела, приточно-вытяжной вентиляции с очисткой воздуха, кондиционирования торгового зала площадью более 8 000 м².',
      image: '/projects/ramstore-mega.jpg',
      mapsUrl: 'https://maps.google.com/?q=Ramstore+Mega+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'ramstore-forum-mall',
      title: 'ТЦ «Ramstore Forum Mall»',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2012,
      description: 'Торговый центр Forum Mall с гипермаркетом Ramstore в микрорайоне Алмагуль. Смонтированы системы климат-контроля для торговых залов, спринклерное пожаротушение, вентиляция с подогревом приточного воздуха в зимний период.',
      image: '/projects/ramstore-forum.jpg',
      mapsUrl: 'https://maps.google.com/?q=Forum+Mall+Almaty',
      status: 'completed',
    },
    {
      id: 'mega-center-almaty',
      title: '«MEGA Center Alma-Ata», Расширение торгового центра',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2013,
      description: 'Расширение крупнейшего торгово-развлекательного центра Алматы общей площадью 170 000 м². Выполнен комплекс инженерных работ для новых торговых площадей: вентиляция, кондиционирование, водоснабжение, автоматическое пожаротушение.',
      image: '/projects/mega-center-almaty.jpg',
      mapsUrl: 'https://maps.google.com/?q=Mega+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'jibek-joly-bc',
      title: 'Бизнес-центр «Жибек Жолы»',
      category: 'Офисы',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Современный бизнес-центр класса А на проспекте Жибек Жолы. Смонтированы системы центрального отопления и кондиционирования, приточно-вытяжная вентиляция с индивидуальным управлением для каждого этажа, сети электроснабжения с резервированием.',
      image: '/projects/jibek-joly.jpg',
      mapsUrl: 'https://maps.google.com/?q=Jibek+Joly+Business+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'astana-group-academy',
      title: '«Astana Group Academy»',
      category: 'Образование',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2023,
      description: 'Корпоративный учебный центр холдинга Astana Group. Выполнен монтаж систем климат-контроля для учебных аудиторий, вентиляции с нормированным воздухообменом, современного освещения, систем безопасности и контроля доступа.',
      image: '/projects/astana-group-academy.jpg',
      mapsUrl: 'https://maps.google.com/?q=Astana+Group+Academy+Almaty',
      status: 'completed',
    },
    {
      id: 'ramstore-samal',
      title: 'Реконструкция ТЦ «Ramstore Samal»',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Реконструкция торгового центра в микрорайоне Самал. Выполнена полная модернизация инженерных систем: замена вентиляционного оборудования, обновление системы кондиционирования, модернизация пожарной сигнализации и автоматики.',
      image: '/projects/ramstore-samal.jpg',
      mapsUrl: 'https://maps.google.com/?q=Ramstore+Samal+Almaty',
      status: 'completed',
    },
    {
      id: 'bloom-house',
      title: 'Жилой комплекс «Bloom House»',
      category: 'Жилой комплекс',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2023,
      description: 'Премиальный жилой комплекс бизнес-класса в престижном районе Алматы. Смонтированы системы индивидуального отопления и кондиционирования, приточно-вытяжная вентиляция с рекуперацией тепла, сети горячего и холодного водоснабжения, системы умного дома.',
      image: '/projects/bloom-house.jpg',
      mapsUrl: 'https://maps.google.com/?q=Bloom+House+Almaty',
      status: 'completed',
    },
    {
      id: 'shymkent-plaza',
      title: 'ТРЦ «Shymkent Plaza»',
      category: 'Торговый центр',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Крупнейший торгово-развлекательный центр Шымкента площадью более 80 000 м². Выполнен полный комплекс инженерных работ: центральное кондиционирование, приточно-вытяжная вентиляция, автоматическое пожаротушение, сети водоснабжения и водоотведения.',
      image: '/projects/shymkent-plaza.jpg',
      mapsUrl: 'https://maps.google.com/?q=Shymkent+Plaza',
      status: 'completed',
    },
    {
      id: 'polpan',
      title: 'Завод изоляционных материалов «Polpan»',
      category: 'Промышленность',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2021,
      description: 'Производственный комплекс по выпуску изоляционных материалов. Смонтированы системы промышленной вентиляции с очисткой воздуха от пыли, электроснабжение производственного оборудования, автоматическая система пожаротушения.',
      image: '/projects/polpan.jpg',
      mapsUrl: 'https://maps.google.com/?q=Polpan+Almaty',
      status: 'completed',
    },
    {
      id: 'kairat-base',
      title: 'Спортивная база ФК «Кайрат»',
      category: 'Спорт',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Тренировочная база профессионального футбольного клуба «Кайрат». Выполнен монтаж систем отопления спортивных залов и раздевалок, вентиляции с контролем влажности, горячего водоснабжения для душевых, системы полива газонов.',
      image: '/projects/kairat-base.jpg',
      mapsUrl: 'https://maps.google.com/?q=Kairat+Training+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'kairat-stadium',
      title: 'Реконструкция центрального стадиона ФК «Кайрат»',
      category: 'Спорт',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2010,
      description: 'Реконструкция домашнего стадиона ФК «Кайрат» вместимостью 23 800 зрителей. Модернизированы системы водоснабжения и канализации, отопление подтрибунных помещений, вентиляция VIP-зон, система автоматического полива газона.',
      image: '/projects/kairat-stadium.jpg',
      mapsUrl: 'https://maps.google.com/?q=Kairat+Stadium+Almaty',
      status: 'completed',
    },
    {
      id: 'logistic-center',
      title: '«Logistic Center»',
      category: 'Промышленность',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Современный логистический комплекс класса А площадью 30 000 м². Смонтированы системы воздушного отопления складских помещений, вентиляции с контролем температуры, автоматическое пожаротушение, сети электроснабжения.',
      image: '/projects/logistic-center.jpg',
      mapsUrl: 'https://maps.google.com/?q=Logistic+Center+Almaty',
      status: 'completed',
    },
    {
      id: 'almaly-office',
      title: '«Almaly Office»',
      category: 'Офисы',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Бизнес-центр в Алмалинском районе Алматы. Выполнен монтаж систем центрального кондиционирования и вентиляции, электроснабжения с резервированием, систем безопасности и контроля доступа, структурированных кабельных сетей.',
      image: '/projects/almaly-office.jpg',
      mapsUrl: 'https://maps.google.com/?q=Almaly+Office+Almaty',
      status: 'completed',
    },
    {
      id: 'zara-store',
      title: 'Магазин «ZARA»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2014,
      description: 'Флагманский магазин ZARA в ТРЦ Достык Плаза площадью более 2 500 м². Смонтированы системы климат-контроля согласно стандартам Inditex Group, приточно-вытяжная вентиляция, спринклерное пожаротушение, современное освещение торгового зала.',
      image: '/projects/zara.jpg',
      mapsUrl: 'https://maps.google.com/?q=ZARA+Almaty',
      status: 'completed',
    },
    {
      id: 'zara-home',
      title: 'Магазин «ZARA Home»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Магазин товаров для дома бренда ZARA Home. Выполнен монтаж систем кондиционирования с поддержанием стабильной температуры, вентиляции с контролем влажности для сохранности текстильной продукции.',
      image: '/projects/zara-home.jpg',
      mapsUrl: 'https://maps.google.com/?q=ZARA+Home+Almaty',
      status: 'completed',
    },
    {
      id: 'stradivarius',
      title: 'Магазины «Stradivarius»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Сеть магазинов молодёжной женской одежды Stradivarius. Смонтированы системы климат-контроля согласно корпоративным стандартам бренда, энергоэффективное освещение, системы вентиляции с фильтрацией воздуха.',
      image: '/projects/stradivarius.jpg',
      mapsUrl: 'https://maps.google.com/?q=Stradivarius+Almaty',
      status: 'completed',
    },
    {
      id: 'oysho',
      title: 'Магазин «Oysho»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Магазин нижнего белья и спортивной одежды Oysho. Выполнен монтаж систем вентиляции с точным контролем температуры в примерочных зонах, кондиционирования торгового зала, электроснабжения освещения и оборудования.',
      image: '/projects/oysho.jpg',
      mapsUrl: 'https://maps.google.com/?q=Oysho+Almaty',
      status: 'completed',
    },
    {
      id: 'pull-bear',
      title: 'Магазин «Pull & Bear»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Магазин молодёжной одежды Pull & Bear в ТРЦ Достык Плаза. Смонтированы системы климат-контроля с индивидуальным управлением зонами, современное LED-освещение, вентиляция с рекуперацией тепла.',
      image: '/projects/pull-bear.jpg',
      mapsUrl: 'https://maps.google.com/?q=Pull+Bear+Almaty',
      status: 'completed',
    },
    {
      id: 'massimo-dutti',
      title: 'Магазин «Massimo Dutti»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Премиальный магазин одежды Massimo Dutti. Выполнен монтаж систем климат-контроля с бесшумным оборудованием, дизайнерского освещения торгового зала, систем безопасности и видеонаблюдения.',
      image: '/projects/massimo-dutti.jpg',
      mapsUrl: 'https://maps.google.com/?q=Massimo+Dutti+Almaty',
      status: 'completed',
    },
    {
      id: 'bershka',
      title: 'Магазин «Bershka»',
      category: 'Ритейл',
      location: 'Алматы, Астана',
      country: 'Казахстан',
      year: 2011,
      description: 'Сеть магазинов молодёжной одежды Bershka в крупнейших торговых центрах Алматы и Астаны. Смонтированы унифицированные системы вентиляции и кондиционирования согласно стандартам Inditex Group.',
      image: '/projects/bershka.jpg',
      mapsUrl: 'https://maps.google.com/?q=Bershka+Almaty',
      status: 'completed',
    },
    {
      id: 'uterque',
      title: 'Магазин «Uterqüe»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2015,
      description: 'Бутик аксессуаров и обуви премиум-класса Uterqüe. Выполнен монтаж систем климат-контроля для витринных зон, освещения с акцентами на товар, вентиляции с контролем влажности.',
      image: '/projects/uterque.jpg',
      mapsUrl: 'https://maps.google.com/?q=Uterque+Almaty',
      status: 'completed',
    },
    {
      id: 'zolotoe-yabloko',
      title: 'Магазин «Золотое Яблоко»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2021,
      description: 'Магазин косметики и парфюмерии федеральной сети «Золотое Яблоко». Смонтированы системы климат-контроля с точным поддержанием температуры для сохранности косметической продукции, вентиляции с фильтрацией запахов.',
      image: '/projects/zolotoe-yabloko.jpg',
      mapsUrl: 'https://maps.google.com/?q=Zolotoe+Yabloko+Almaty',
      status: 'completed',
    },
    {
      id: 'reserved',
      title: 'Магазин «Reserved»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2017,
      description: 'Магазин одежды польского бренда Reserved группы LPP. Выполнен монтаж систем приточно-вытяжной вентиляции согласно европейским стандартам, кондиционирования торгового зала площадью более 1 500 м².',
      image: '/projects/reserved.jpg',
      mapsUrl: 'https://maps.google.com/?q=Reserved+Almaty',
      status: 'completed',
    },
    {
      id: 'space-multimedia',
      title: 'Магазин «Space Multimedia»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Мультибрендовый магазин электроники и бытовой техники. Смонтированы системы климат-контроля с защитой от перегрева оборудования, электроснабжение витрин и демонстрационных зон, современное освещение.',
      image: '/projects/space-multimedia.jpg',
      mapsUrl: 'https://maps.google.com/?q=Space+Multimedia+Almaty',
      status: 'completed',
    },
    {
      id: 'cinemax-dostyk',
      title: '«Cinemax Dostyk Multiplex»',
      category: 'Развлечения',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2014,
      description: 'Мультиплекс кинотеатра Cinemax на 8 залов в ТРЦ Достык Плаза. Выполнен монтаж бесшумных систем вентиляции и кондиционирования кинозалов, подготовка помещений для акустической обработки, противопожарные системы.',
      image: '/projects/cinemax-dostyk.jpg',
      mapsUrl: 'https://maps.google.com/?q=Cinemax+Dostyk+Almaty',
      status: 'completed',
    },
    {
      id: 'marwin-shymkent',
      title: 'Магазин «Marwin»',
      category: 'Ритейл',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Гипермаркет детских товаров и игрушек Marwin в ТРЦ Shymkent Plaza. Смонтированы системы климат-контроля с повышенной безопасностью для детской зоны, яркое освещение торгового зала, вентиляция с очисткой воздуха.',
      image: '/projects/marwin.jpg',
      mapsUrl: 'https://maps.google.com/?q=Marwin+Shymkent',
      status: 'completed',
    },
    {
      id: 'newyorker-shymkent',
      title: 'Магазин «NewYorker»',
      category: 'Ритейл',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Магазин молодёжной одежды немецкого бренда NewYorker. Выполнен монтаж систем вентиляции и кондиционирования согласно корпоративным стандартам, энергоэффективного освещения торгового зала.',
      image: '/projects/newyorker.jpg',
      mapsUrl: 'https://maps.google.com/?q=NewYorker+Shymkent',
      status: 'completed',
    },
    {
      id: 'sulpak-shymkent',
      title: 'Магазин «Sulpak»',
      category: 'Ритейл',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Гипермаркет электроники и бытовой техники Sulpak площадью более 3 000 м². Смонтированы системы климат-контроля для демонстрационных зон техники, мощное электроснабжение витрин, современное освещение.',
      image: '/projects/sulpak.jpg',
      mapsUrl: 'https://maps.google.com/?q=Sulpak+Shymkent',
      status: 'completed',
    },
    {
      id: 'koton-shymkent',
      title: 'Магазин «Koton»',
      category: 'Ритейл',
      location: 'Шымкент, Казахстан',
      country: 'Казахстан',
      year: 2016,
      description: 'Магазин турецкого бренда одежды Koton. Выполнен монтаж систем приточно-вытяжной вентиляции, кондиционирования с индивидуальным управлением зонами, современного LED-освещения.',
      image: '/projects/koton.jpg',
      mapsUrl: 'https://maps.google.com/?q=Koton+Shymkent',
      status: 'completed',
    },
    {
      id: 'mavi-almaty',
      title: 'Магазин «Mavi»',
      category: 'Ритейл',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2018,
      description: 'Магазин джинсовой одежды турецкого бренда Mavi Jeans. Смонтированы системы климат-контроля для сохранности текстильной продукции, современное освещение с акцентами на коллекции, вентиляция примерочных зон.',
      image: '/projects/mavi.jpg',
      mapsUrl: 'https://maps.google.com/?q=Mavi+Almaty',
      status: 'completed',
    },
    {
      id: 'chaplin-cinemas',
      title: '«Chaplin Cinemas»',
      category: 'Развлечения',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2022,
      description: 'Сеть кинотеатров Chaplin Cinemas в Алматы. Выполнен монтаж бесшумных систем вентиляции для кинозалов с нормированным воздухообменом, кондиционирования, подготовка помещений под акустическую обработку.',
      image: '/projects/chaplin.jpg',
      mapsUrl: 'https://maps.google.com/?q=Chaplin+Cinemas+Almaty',
      status: 'completed',
    },
    {
      id: 'mega-silk-way',
      title: 'ТРЦ «MEGA Silk Way»',
      category: 'Торговый центр',
      location: 'Астана, Казахстан',
      country: 'Казахстан',
      year: 2017,
      description: 'Крупнейший торгово-развлекательный центр Центральной Азии общей площадью 350 000 м², расположенный на левом берегу Астаны. Выполнен полный комплекс инженерных работ: центральное кондиционирование торговых галерей, приточно-вытяжная вентиляция с рекуперацией тепла, автоматическое спринклерное пожаротушение, сети холодного и горячего водоснабжения.',
      image: '/projects/mega-silk-way.jpg',
      mapsUrl: 'https://maps.google.com/?q=Mega+Silk+Way+Astana',
      status: 'completed',
    },
    {
      id: 'dostyk-plaza',
      title: 'ТРЦ «Достык Плаза»',
      category: 'Торговый центр',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2014,
      description: 'Премиальный торгово-развлекательный центр на проспекте Достык площадью 65 000 м². Смонтированы системы центрального кондиционирования с чиллерным оборудованием, приточно-вытяжная вентиляция торговых галерей, автоматическое пожаротушение, сети водоснабжения и канализации для арендаторов и фуд-корта.',
      image: '/projects/dostyk-plaza.jpg',
      mapsUrl: 'https://maps.google.com/?q=Dostyk+Plaza+Almaty',
      status: 'completed',
    },
    {
      id: 'nef-uptown',
      title: 'ЖК «NEF Uptown»',
      category: 'Жилой комплекс',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2024,
      description: 'Премиальный жилой комплекс от турецкого застройщика NEF в верхней части города. Выполняется монтаж инженерных систем для жилых башен: индивидуальное поквартирное отопление, приточно-вытяжная вентиляция с рекуперацией, сети холодного и горячего водоснабжения, системы умного дома.',
      image: '/projects/nef-uptown.jpg',
      mapsUrl: 'https://maps.google.com/?q=NEF+Uptown+Almaty',
      status: 'in_progress',
    },
    {
      id: 'turkestan-residential',
      title: 'ЖК «Туркестан»',
      category: 'Жилой комплекс',
      location: 'Туркестан, Казахстан',
      country: 'Казахстан',
      year: 2024,
      description: 'Многоэтажный жилой комплекс в городе Туркестан, строящийся в рамках программы развития региона. Выполняется монтаж инженерных систем: центральное отопление от теплового пункта, внутренние сети холодного и горячего водоснабжения, канализация, вентиляция подземной парковки.',
      image: '/projects/turkestan.jpg',
      mapsUrl: 'https://maps.google.com/?q=Turkestan,+Kazakhstan',
      status: 'in_progress',
    },
    {
      id: 'hilton-garden-inn',
      title: 'Отель «Hilton Garden Inn»',
      category: 'Гостиница',
      location: 'Алматы, Казахстан',
      country: 'Казахстан',
      year: 2017,
      description: 'Гостиница международной сети Hilton на 200 номеров в центре Алматы. Выполнен монтаж инженерных систем согласно международным стандартам бренда: центральное кондиционирование с индивидуальным управлением для каждого номера, приточно-вытяжная вентиляция, автоматическое пожаротушение, сети горячего и холодного водоснабжения.',
      image: '/projects/hilton-almaty.jpg',
      mapsUrl: 'https://maps.google.com/?q=Hilton+Garden+Inn+Almaty',
      status: 'completed',
    },
  ],

  certificates: [
    { id: 'cert-1', company: 'TORO Construction', image: '/certificates/toro-construction.jpg', year: 2016, type: 'recommendation' },
    { id: 'cert-2', company: 'Real Estate & Construction Group', image: '/certificates/real-estate.jpg', year: 2016, type: 'recommendation' },
    { id: 'cert-3', company: 'TS Development Shymkent', image: '/certificates/ts-development.jpg', year: 2016, type: 'recommendation' },
    { id: 'cert-4', company: 'TAV Construction', image: '/certificates/tav-construction.jpg', year: 2024, type: 'recommendation' },
    { id: 'cert-5', company: 'POLPAN Insulation KZ', image: '/certificates/polpan.jpg', year: 2016, type: 'recommendation' },
    { id: 'cert-6', company: 'TS Стройсервис', image: '/certificates/ts-stroyservice.jpg', year: 2016, type: 'recommendation' },
  ],

  process: [
    { id: 'step-1', number: 1, title: 'Заявка', description: 'Свяжитесь с нами для обсуждения проекта' },
    { id: 'step-2', number: 2, title: 'Анализ', description: 'Изучаем техническое задание и объект' },
    { id: 'step-3', number: 3, title: 'Проект', description: 'Разрабатываем проектную документацию' },
    { id: 'step-4', number: 4, title: 'Реализация', description: 'Выполняем монтажные работы' },
    { id: 'step-5', number: 5, title: 'Сдача', description: 'Передаём объект с документацией и гарантией' },
  ],

  faq: [
    {
      id: 'faq-1',
      question: 'В каких регионах вы работаете?',
      answer: 'Выполняем проекты по всему Казахстану и странам СНГ: Узбекистан, Таджикистан, Кыргызстан.',
    },
    {
      id: 'faq-2',
      question: 'С какими объектами вы работаете?',
      answer: 'Специализируемся на промышленных объектах, аэропортах, торговых центрах, жилых комплексах.',
    },
    {
      id: 'faq-3',
      question: 'Какие гарантии вы предоставляете?',
      answer: 'Гарантия на все виды работ согласно договору. Гарантийное и постгарантийное обслуживание.',
    },
    {
      id: 'faq-4',
      question: 'Как происходит оплата?',
      answer: 'Работаем по договору с поэтапной оплатой. Аванс, промежуточные платежи и расчёт после сдачи.',
    },
  ],

  contacts: {
    phone: '+7 (727) 248-34-54',
    email: 'info@timstroy.kz',
    address: {
      city: 'Алматы',
      street: 'ул. Жибек Жолы, 135',
      building: 'БЦ «Жибек Жолы», Блок 1, этаж 10',
      district: 'Алмалинский район',
      coords: { lat: 43.2567, lng: 76.9286 },
    },
    workingHours: {
      weekdays: 'Пн–Сб: 8:30–18:00',
      weekend: 'Вс — выходной',
    },
  },

  seo: {
    title: 'TIM STROY — Инженерно-строительная компания | Казахстан',
    description: 'TIM STROY — проектирование и монтаж инженерных систем для промышленных объектов, аэропортов, жилых комплексов. Казахстан и СНГ.',
    keywords: ['инженерные системы', 'водоснабжение', 'вентиляция', 'строительство', 'TIM STROY', 'Алматы'],
  },
};
